### DISCUSSION TITLE
How to use instead of helm charts

### DISCUSSION THREAD

**Discussion by Devanshu24** [ZCube/bitnami-compat#25] [Q&A] [answered]
I am using a repo that defines the helm charts as follows. Now that I want to use `bitnami-compact` instead of these, how should I go about changing the config file?
```yaml
  - mongodb:
      helm:
        repo:
          name: bitnami
          url: https://charts.bitnami.com/bitnami
        chart: mongodb
        install_args: |
          --set auth.enabled=false
  - localstack:
      helm:
        repo:
          name: localstack-charts
          url: https://localstack.github.io/helm-charts
        chart: localstack
        install_args: |
          --set startServices=dynamod
```
Apologies for the naive question, I am very new to helm. I did refer to the [Usage 2](https://github.com/ZCube/bitnami-compat#usage-2) section on the README but could not understand how to port it to this style of configuration.

Any help will be much appreciated!

cc: @ZCube

**Comment by zcube** [comment, marked as answer]
If you refer to the values.yaml file, you can replace the image with:

https://github.com/bitnami/charts/blob/master/bitnami/mongodb/values.yaml
```
image:
  registry: docker.io
  repository: bitnami/mongodb
  tag: 5.0.10-debian-11-r1
```
->
```
image:
  registry: ghcr.io
  repository: zcube/bitnami-compat/mongodb
  tag: 5.0.9-debian-11-r18
```

You can set these as options as follows:
```
        install_args: |
          --set auth.enabled=false
```
->
```
        install_args: |
          --set auth.enabled=false
          --set image.registry=ghcr.io
          --set image.repository=zcube/bitnami-compat/mongodb
          --set image.tag=5.0.9-debian-11-r18
```
