### ISSUE TITLE
Request for bitnami/keycloak-config-cli

### ISSUE THREAD

**Issue by roderik** [ZCube/bitnami-compat#22]
I use it in the helm chart to preconfigure the realm, but it just does nothing when running the and version. 

It does not look like there is anything difficult installed (java and a jar file) but I don't really know how to get started on a PR.

```
  keycloakConfigCli:
    enabled: true
    backoffLimit: 3
    # https://github.com/bitnami/charts/issues/10796
    command:
      - java
      - -jar
      - /opt/bitnami/keycloak-config-cli/keycloak-config-cli-18.0.1.jar
    extraVolumes:
      - name: secret-volume
        secret:
          secretName: secondary-keycloak-config
    extraVolumeMounts:
      - name: secret-volume
        mountPath: "/custom-config"
        readOnly: true
    extraEnvVars:
      - name: IMPORT_FILES_LOCATIONS
        value: /custom-config/*
```
