### ISSUE TITLE
galera support

### ISSUE THREAD

**Issue by unixfox** [ZCube/bitnami-compat#3]
Would galera docker image: https://hub.docker.com/r/bitnami/mariadb-galera work with bitnami-compat?
If so is it possible to add the support for this image?

**Comment by ZCube** [comment]
@unixfox Galera seems a bit complicated image. Study is needed It will be difficult soon, but I'll see when I have time.

**Comment by ZCube** [comment]
@unixfox added But it's hard to test because I haven't used this image yet.

**Comment by unixfox** [comment]
I just tried and unfortunately it doesn't fully work, the containers boots up, but it is missing some librairies for the MariaDB replication:
```
galera-mariadb-galera-1-1  | 2022-02-10 16:09:26 0 [Note] /opt/bitnami/mariadb/sbin/mysqld (server 10.6.5-MariaDB-1:10.6.5+maria~buster-log) starting as process 1 ...
galera-mariadb-galera-1-1  | 2022-02-10 16:09:26 0 [Note] WSREP: Loading provider /opt/bitnami/mariadb/lib/libgalera_smm.so initial position: 00000000-0000-0000-0000-000000000000:-1
galera-mariadb-galera-1-1  | 2022-02-10 16:09:26 0 [Note] WSREP: wsrep_load(): loading provider library '/opt/bitnami/mariadb/lib/libgalera_smm.so'
galera-mariadb-galera-1-1  | 2022-02-10 16:09:26 0 [ERROR] WSREP: wsrep_load(): dlopen(): /opt/bitnami/mariadb/lib/libgalera_smm.so: cannot open shared object file: No such file or directory
galera-mariadb-galera-1-1  | 2022-02-10 16:09:26 0 [ERROR] WSREP: Failed to create a new provider '/opt/bitnami/mariadb/lib/libgalera_smm.so' with options '': Failed to load wsrep library
galera-mariadb-galera-1-1  | 2022-02-10 16:09:26 0 [ERROR] WSREP: Failed to load provider
galera-mariadb-galera-1-1  | 2022-02-10 16:09:26 0 [ERROR] Aborting
```

Here is an example docker-compose file if you want to test:
```yml
version: '2.3'

services:
  mariadb-galera-0:
    image: ghcr.io/zcube/bitnami-compat/mariadb-galera:10.6
    environment:
      - MARIADB_GALERA_CLUSTER_NAME=galera
      - MARIADB_GALERA_MARIABACKUP_USER=my_mariabackup_user
      - MARIADB_GALERA_MARIABACKUP_PASSWORD=my_mariabackup_password
      - MARIADB_ROOT_PASSWORD=P4SSW0RD123
      - MARIADB_USER=my_user
      - MARIADB_PASSWORD=my_password
      - MARIADB_DATABASE=my_database
      - MARIADB_REPLICATION_USER=my_replication_user
      - MARIADB_REPLICATION_PASSWORD=my_replication_password
    volumes:
      - 'mariadb_galera_data_0:/bitnami/mariadb'
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb-galera/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
  mariadb-galera-1:
    image: ghcr.io/zcube/bitnami-compat/mariadb-galera:10.6
    command:
      - bash
      - -ec
      - |
          # Wait 20 seconds to guarantee creation order
          sleep 20
          exec /opt/bitnami/scripts/mariadb-galera/entrypoint.sh /opt/bitnami/scripts/mariadb-galera/run.sh
    environment:
      - MARIADB_GALERA_CLUSTER_NAME=galera
      - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://mariadb-galera-0:4567,0.0.0.0:4567
      - MARIADB_GALERA_MARIABACKUP_USER=my_mariabackup_user
      - MARIADB_GALERA_MARIABACKUP_PASSWORD=my_mariabackup_password
      - MARIADB_ROOT_PASSWORD=P4SSW0RD123
      - MARIADB_REPLICATION_USER=my_replication_user
      - MARIADB_REPLICATION_PASSWORD=my_replication_password
    volumes:
      - 'mariadb_galera_data_1:/bitnami/mariadb'
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb-galera/healthcheck.sh']
      start_period: 20s
      interval: 15s
      timeout: 5s
      retries: 6
    depends_on:
      - mariadb-galera-0

volumes:
  mariadb_galera_data_0:
    driver: local
  mariadb_galera_data_1:
    driver: local
```
