### ISSUE TITLE
Build Keycloak v19

### ISSUE THREAD

**Issue by roderik** [ZCube/bitnami-compat#31]
There is a new v19 Keycloak folder which is not part of the build process

**Comment by roderik** [comment]
FYI, when running 18 under the following security contexts, it has a permission denied on the keycloak.conf file

```
  podSecurityContext:
    enabled: true
    runAsNonRoot: true
    runAsUser: 2016
    fsGroup: 2016
  containerSecurityContext:
    enabled: true
    runAsNonRoot: true
    runAsUser: 2016
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    seccompProfile:
      type: RuntimeDefault
```

The official 19 image does not
