### ISSUE TITLE
Postgresql image (15.1.0-debian-11-r19)

### ISSUE THREAD

**Issue by nodesocket** [ZCube/bitnami-compat#53]
Trying to use:

```yaml
image:
  registry: ghcr.io  # required for arm64
  repository: zcube/bitnami-compat/postgresql  # required for arm64
  tag: 15.1.0-debian-11-r19
```

But getting `Error response from daemon: manifest unknown`.
